### PR TITLE
Add handling relative paths

### PR DESCRIPTION
**Pull request by x-yuri**

### CODE REVIEW

**Comment by s0ber** [comment]
Hello, @x-yuri! Thanks, that looks very nice. I have just a single concern. Usually I am using this tool with `sass-loader` (in webpack) and they have a special syntax for specifying absolute paths:
https://github.com/webpack-contrib/sass-loader#imports

In this case those will paths, which are relative to `node_modules`, or other custom lookup paths. But, for example, in sprockets they are using `/` sign for absolute paths.

So I suggest to allow to use both absolute and relative paths. To have an ability to specify `assetsPath` and still use relative paths too.

And we can distinguish absolute paths from relative with simple rule. Absolute path should have `~` or `/` at the beginning.

**Comment by x-yuri** [comment]
Let's decide on terminology first. Absolute paths are paths relative to dirs in  `assetsPath`. Relative paths are paths relative to the css file being processed.

Having that said, you have absolute paths in tests, not starting with `/` (like `img/test_image.jpg`). So supposedly these kinds of paths will become relative after having done what you suggest. Just confirming if we're on the same page.

For now I made relative paths a fallback for case when image can't be found in `assetsPath`. But now that I think about it, to be able to easily distinguish absolute path from relative ones is a good thing to have. On the other hand paths not starting with `/` becoming relative might break some code.

What do you say?

**Comment by s0ber** [comment]
@x-yuri You're right, right now we treat all paths as absolute. I suggest to start treating path as an absolute, only if it starts with `/` or `~`. Also, let's just start new "minor" version, something like `0.1.0`.

**Comment by x-yuri** [comment]
@s0ber I did as you suggested, check if it's okay, please.

**Comment by s0ber** [comment]
Looks good to me 👍 
Thanks for this a lot! I'll add info about paths to README and will merge and publish it in an hour.

**Comment by s0ber** [comment]
@x-yuri Published to npm.

**Pull request merged**
